//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.05 at 10:41:30 AM EDT 
//


package com.tie.xmlprocessor.cbcrxmlprocessor.cbcrxmljaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CbcBody_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CbcBody_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ReportingEntity" type="{urn:oecd:ties:cbc:v1}CorrectableReportingEntity_Type" minOccurs="0"/>
 *         &lt;element name="CbcReports" type="{urn:oecd:ties:cbc:v1}CorrectableCbcReport_Type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AdditionalInfo" type="{urn:oecd:ties:cbc:v1}CorrectableAdditionalInfo_Type" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CbcBody_Type", propOrder = {
    "reportingEntity",
    "cbcReports",
    "additionalInfo"
})
public class CbcBodyType {

    @XmlElement(name = "ReportingEntity")
    protected CorrectableReportingEntityType reportingEntity;
    @XmlElement(name = "CbcReports")
    protected List<CorrectableCbcReportType> cbcReports;
    @XmlElement(name = "AdditionalInfo")
    protected List<CorrectableAdditionalInfoType> additionalInfo;

    /**
     * Gets the value of the reportingEntity property.
     * 
     * @return
     *     possible object is
     *     {@link CorrectableReportingEntityType }
     *     
     */
    public CorrectableReportingEntityType getReportingEntity() {
        return reportingEntity;
    }

    /**
     * Sets the value of the reportingEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link CorrectableReportingEntityType }
     *     
     */
    public void setReportingEntity(CorrectableReportingEntityType value) {
        this.reportingEntity = value;
    }

    /**
     * Gets the value of the cbcReports property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cbcReports property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCbcReports().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CorrectableCbcReportType }
     * 
     * 
     */
    public List<CorrectableCbcReportType> getCbcReports() {
        if (cbcReports == null) {
            cbcReports = new ArrayList<CorrectableCbcReportType>();
        }
        return this.cbcReports;
    }

    /**
     * Gets the value of the additionalInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionalInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionalInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CorrectableAdditionalInfoType }
     * 
     * 
     */
    public List<CorrectableAdditionalInfoType> getAdditionalInfo() {
        if (additionalInfo == null) {
            additionalInfo = new ArrayList<CorrectableAdditionalInfoType>();
        }
        return this.additionalInfo;
    }

}
