//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.05 at 10:41:30 AM EDT 
//


package com.tie.xmlprocessor.cbcrxmlprocessor.cbcrxmljaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CbcMessageTypeIndic_EnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CbcMessageTypeIndic_EnumType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="CBC401"/>
 *     &lt;enumeration value="CBC402"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CbcMessageTypeIndic_EnumType")
@XmlEnum
public enum CbcMessageTypeIndicEnumType {


    /**
     * The message contains new information
     * 
     */
    @XmlEnumValue("CBC401")
    CBC_401("CBC401"),

    /**
     * The message contains corrections for previously sent information
     * 
     */
    @XmlEnumValue("CBC402")
    CBC_402("CBC402");
    private final String value;

    CbcMessageTypeIndicEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CbcMessageTypeIndicEnumType fromValue(String v) {
        for (CbcMessageTypeIndicEnumType c: CbcMessageTypeIndicEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
