//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.05 at 10:41:30 AM EDT 
//


package com.tie.xmlprocessor.cbcrxmlprocessor.cbcrxmljaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CbcSummaryListElementsType_EnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CbcSummaryListElementsType_EnumType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="CBC601"/>
 *     &lt;enumeration value="CBC602"/>
 *     &lt;enumeration value="CBC603"/>
 *     &lt;enumeration value="CBC604"/>
 *     &lt;enumeration value="CBC605"/>
 *     &lt;enumeration value="CBC606"/>
 *     &lt;enumeration value="CBC607"/>
 *     &lt;enumeration value="CBC608"/>
 *     &lt;enumeration value="CBC609"/>
 *     &lt;enumeration value="CBC610"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CbcSummaryListElementsType_EnumType")
@XmlEnum
public enum CbcSummaryListElementsTypeEnumType {


    /**
     * Revenues - Unrelated
     * 
     */
    @XmlEnumValue("CBC601")
    CBC_601("CBC601"),

    /**
     * Revenues - Related
     * 
     */
    @XmlEnumValue("CBC602")
    CBC_602("CBC602"),

    /**
     * Revenues - Total
     * 
     */
    @XmlEnumValue("CBC603")
    CBC_603("CBC603"),

    /**
     * Profit or Loss
     * 
     */
    @XmlEnumValue("CBC604")
    CBC_604("CBC604"),

    /**
     * Tax Paid
     * 
     */
    @XmlEnumValue("CBC605")
    CBC_605("CBC605"),

    /**
     * Tax Accrued
     * 
     */
    @XmlEnumValue("CBC606")
    CBC_606("CBC606"),

    /**
     * Capital
     * 
     */
    @XmlEnumValue("CBC607")
    CBC_607("CBC607"),

    /**
     * Earnings
     * 
     */
    @XmlEnumValue("CBC608")
    CBC_608("CBC608"),

    /**
     * Number of Employees
     * 
     */
    @XmlEnumValue("CBC609")
    CBC_609("CBC609"),

    /**
     * Assets
     * 
     */
    @XmlEnumValue("CBC610")
    CBC_610("CBC610");
    private final String value;

    CbcSummaryListElementsTypeEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CbcSummaryListElementsTypeEnumType fromValue(String v) {
        for (CbcSummaryListElementsTypeEnumType c: CbcSummaryListElementsTypeEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
