//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.05 at 10:41:30 AM EDT 
//


package com.tie.xmlprocessor.cbcrxmlprocessor.cbcrxmljaxb;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CorrectableCbcReport_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CorrectableCbcReport_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DocSpec" type="{urn:oecd:ties:stf:v4}DocSpec_Type"/>
 *         &lt;element name="ResCountryCode" type="{urn:oecd:ties:isocbctypes:v1}CountryCode_Type"/>
 *         &lt;element name="Summary">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Revenues">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Unrelated" type="{urn:oecd:ties:cbc:v1}MonAmnt_Type"/>
 *                             &lt;element name="Related" type="{urn:oecd:ties:cbc:v1}MonAmnt_Type"/>
 *                             &lt;element name="Total" type="{urn:oecd:ties:cbc:v1}MonAmnt_Type"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="ProfitOrLoss" type="{urn:oecd:ties:cbc:v1}MonAmnt_Type"/>
 *                   &lt;element name="TaxPaid" type="{urn:oecd:ties:cbc:v1}MonAmnt_Type"/>
 *                   &lt;element name="TaxAccrued" type="{urn:oecd:ties:cbc:v1}MonAmnt_Type"/>
 *                   &lt;element name="Capital" type="{urn:oecd:ties:cbc:v1}MonAmnt_Type"/>
 *                   &lt;element name="Earnings" type="{urn:oecd:ties:cbc:v1}MonAmnt_Type"/>
 *                   &lt;element name="NbEmployees" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="Assets" type="{urn:oecd:ties:cbc:v1}MonAmnt_Type"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ConstEntities" type="{urn:oecd:ties:cbc:v1}ConstituentEntity_Type" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CorrectableCbcReport_Type", propOrder = {
    "docSpec",
    "resCountryCode",
    "summary",
    "constEntities"
})
public class CorrectableCbcReportType {

    @XmlElement(name = "DocSpec", required = true)
    protected DocSpecType docSpec;
    @XmlElement(name = "ResCountryCode", required = true)
    protected CountryCodeType resCountryCode;
    @XmlElement(name = "Summary", required = true)
    protected CorrectableCbcReportType.Summary summary;
    @XmlElement(name = "ConstEntities", required = true)
    protected List<ConstituentEntityType> constEntities;

    /**
     * Gets the value of the docSpec property.
     * 
     * @return
     *     possible object is
     *     {@link DocSpecType }
     *     
     */
    public DocSpecType getDocSpec() {
        return docSpec;
    }

    /**
     * Sets the value of the docSpec property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocSpecType }
     *     
     */
    public void setDocSpec(DocSpecType value) {
        this.docSpec = value;
    }

    /**
     * Gets the value of the resCountryCode property.
     * 
     * @return
     *     possible object is
     *     {@link CountryCodeType }
     *     
     */
    public CountryCodeType getResCountryCode() {
        return resCountryCode;
    }

    /**
     * Sets the value of the resCountryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CountryCodeType }
     *     
     */
    public void setResCountryCode(CountryCodeType value) {
        this.resCountryCode = value;
    }

    /**
     * Gets the value of the summary property.
     * 
     * @return
     *     possible object is
     *     {@link CorrectableCbcReportType.Summary }
     *     
     */
    public CorrectableCbcReportType.Summary getSummary() {
        return summary;
    }

    /**
     * Sets the value of the summary property.
     * 
     * @param value
     *     allowed object is
     *     {@link CorrectableCbcReportType.Summary }
     *     
     */
    public void setSummary(CorrectableCbcReportType.Summary value) {
        this.summary = value;
    }

    /**
     * Gets the value of the constEntities property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the constEntities property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConstEntities().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConstituentEntityType }
     * 
     * 
     */
    public List<ConstituentEntityType> getConstEntities() {
        if (constEntities == null) {
            constEntities = new ArrayList<ConstituentEntityType>();
        }
        return this.constEntities;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Revenues">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Unrelated" type="{urn:oecd:ties:cbc:v1}MonAmnt_Type"/>
     *                   &lt;element name="Related" type="{urn:oecd:ties:cbc:v1}MonAmnt_Type"/>
     *                   &lt;element name="Total" type="{urn:oecd:ties:cbc:v1}MonAmnt_Type"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="ProfitOrLoss" type="{urn:oecd:ties:cbc:v1}MonAmnt_Type"/>
     *         &lt;element name="TaxPaid" type="{urn:oecd:ties:cbc:v1}MonAmnt_Type"/>
     *         &lt;element name="TaxAccrued" type="{urn:oecd:ties:cbc:v1}MonAmnt_Type"/>
     *         &lt;element name="Capital" type="{urn:oecd:ties:cbc:v1}MonAmnt_Type"/>
     *         &lt;element name="Earnings" type="{urn:oecd:ties:cbc:v1}MonAmnt_Type"/>
     *         &lt;element name="NbEmployees" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="Assets" type="{urn:oecd:ties:cbc:v1}MonAmnt_Type"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "revenues",
        "profitOrLoss",
        "taxPaid",
        "taxAccrued",
        "capital",
        "earnings",
        "nbEmployees",
        "assets"
    })
    public static class Summary {

        @XmlElement(name = "Revenues", required = true)
        protected CorrectableCbcReportType.Summary.Revenues revenues;
        @XmlElement(name = "ProfitOrLoss", required = true)
        protected MonAmntType profitOrLoss;
        @XmlElement(name = "TaxPaid", required = true)
        protected MonAmntType taxPaid;
        @XmlElement(name = "TaxAccrued", required = true)
        protected MonAmntType taxAccrued;
        @XmlElement(name = "Capital", required = true)
        protected MonAmntType capital;
        @XmlElement(name = "Earnings", required = true)
        protected MonAmntType earnings;
        @XmlElement(name = "NbEmployees", required = true)
        protected BigInteger nbEmployees;
        @XmlElement(name = "Assets", required = true)
        protected MonAmntType assets;

        /**
         * Gets the value of the revenues property.
         * 
         * @return
         *     possible object is
         *     {@link CorrectableCbcReportType.Summary.Revenues }
         *     
         */
        public CorrectableCbcReportType.Summary.Revenues getRevenues() {
            return revenues;
        }

        /**
         * Sets the value of the revenues property.
         * 
         * @param value
         *     allowed object is
         *     {@link CorrectableCbcReportType.Summary.Revenues }
         *     
         */
        public void setRevenues(CorrectableCbcReportType.Summary.Revenues value) {
            this.revenues = value;
        }

        /**
         * Gets the value of the profitOrLoss property.
         * 
         * @return
         *     possible object is
         *     {@link MonAmntType }
         *     
         */
        public MonAmntType getProfitOrLoss() {
            return profitOrLoss;
        }

        /**
         * Sets the value of the profitOrLoss property.
         * 
         * @param value
         *     allowed object is
         *     {@link MonAmntType }
         *     
         */
        public void setProfitOrLoss(MonAmntType value) {
            this.profitOrLoss = value;
        }

        /**
         * Gets the value of the taxPaid property.
         * 
         * @return
         *     possible object is
         *     {@link MonAmntType }
         *     
         */
        public MonAmntType getTaxPaid() {
            return taxPaid;
        }

        /**
         * Sets the value of the taxPaid property.
         * 
         * @param value
         *     allowed object is
         *     {@link MonAmntType }
         *     
         */
        public void setTaxPaid(MonAmntType value) {
            this.taxPaid = value;
        }

        /**
         * Gets the value of the taxAccrued property.
         * 
         * @return
         *     possible object is
         *     {@link MonAmntType }
         *     
         */
        public MonAmntType getTaxAccrued() {
            return taxAccrued;
        }

        /**
         * Sets the value of the taxAccrued property.
         * 
         * @param value
         *     allowed object is
         *     {@link MonAmntType }
         *     
         */
        public void setTaxAccrued(MonAmntType value) {
            this.taxAccrued = value;
        }

        /**
         * Gets the value of the capital property.
         * 
         * @return
         *     possible object is
         *     {@link MonAmntType }
         *     
         */
        public MonAmntType getCapital() {
            return capital;
        }

        /**
         * Sets the value of the capital property.
         * 
         * @param value
         *     allowed object is
         *     {@link MonAmntType }
         *     
         */
        public void setCapital(MonAmntType value) {
            this.capital = value;
        }

        /**
         * Gets the value of the earnings property.
         * 
         * @return
         *     possible object is
         *     {@link MonAmntType }
         *     
         */
        public MonAmntType getEarnings() {
            return earnings;
        }

        /**
         * Sets the value of the earnings property.
         * 
         * @param value
         *     allowed object is
         *     {@link MonAmntType }
         *     
         */
        public void setEarnings(MonAmntType value) {
            this.earnings = value;
        }

        /**
         * Gets the value of the nbEmployees property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getNbEmployees() {
            return nbEmployees;
        }

        /**
         * Sets the value of the nbEmployees property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setNbEmployees(BigInteger value) {
            this.nbEmployees = value;
        }

        /**
         * Gets the value of the assets property.
         * 
         * @return
         *     possible object is
         *     {@link MonAmntType }
         *     
         */
        public MonAmntType getAssets() {
            return assets;
        }

        /**
         * Sets the value of the assets property.
         * 
         * @param value
         *     allowed object is
         *     {@link MonAmntType }
         *     
         */
        public void setAssets(MonAmntType value) {
            this.assets = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Unrelated" type="{urn:oecd:ties:cbc:v1}MonAmnt_Type"/>
         *         &lt;element name="Related" type="{urn:oecd:ties:cbc:v1}MonAmnt_Type"/>
         *         &lt;element name="Total" type="{urn:oecd:ties:cbc:v1}MonAmnt_Type"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "unrelated",
            "related",
            "total"
        })
        public static class Revenues {

            @XmlElement(name = "Unrelated", required = true)
            protected MonAmntType unrelated;
            @XmlElement(name = "Related", required = true)
            protected MonAmntType related;
            @XmlElement(name = "Total", required = true)
            protected MonAmntType total;

            /**
             * Gets the value of the unrelated property.
             * 
             * @return
             *     possible object is
             *     {@link MonAmntType }
             *     
             */
            public MonAmntType getUnrelated() {
                return unrelated;
            }

            /**
             * Sets the value of the unrelated property.
             * 
             * @param value
             *     allowed object is
             *     {@link MonAmntType }
             *     
             */
            public void setUnrelated(MonAmntType value) {
                this.unrelated = value;
            }

            /**
             * Gets the value of the related property.
             * 
             * @return
             *     possible object is
             *     {@link MonAmntType }
             *     
             */
            public MonAmntType getRelated() {
                return related;
            }

            /**
             * Sets the value of the related property.
             * 
             * @param value
             *     allowed object is
             *     {@link MonAmntType }
             *     
             */
            public void setRelated(MonAmntType value) {
                this.related = value;
            }

            /**
             * Gets the value of the total property.
             * 
             * @return
             *     possible object is
             *     {@link MonAmntType }
             *     
             */
            public MonAmntType getTotal() {
                return total;
            }

            /**
             * Sets the value of the total property.
             * 
             * @param value
             *     allowed object is
             *     {@link MonAmntType }
             *     
             */
            public void setTotal(MonAmntType value) {
                this.total = value;
            }

        }

    }

}
